import {
  CLIPS_PATH,
  DEVICE_INFO_PATH,
  FREE_BOARD_PATH,
  DEV_LOG_PATH,
  PICS_PATH,
  PIC_LOG_PATH,
} from '@/constants/app';
import type {
  ContentDeletePermission,
  ContentEditPermission,
  ContentSettingRecord,
  ContentSettingStatus,
  ContentViewPermission,
  ContentWritePermission,
  ReportReason,
  ReportStatus,
} from '@/types/domain';

export const defaultContentSettings: Omit<ContentSettingRecord, 'id' | 'collectionId' | 'collectionName' | 'created' | 'updated'>[] = [
  {
    contentKey: 'freeBoard',
    label: '자유게시판',
    group: 'lounge',
    contentType: 'board',
    listPath: FREE_BOARD_PATH,
    writePermission: 'verifiedUser',
    editPermission: 'authorAndAdmin',
    deletePermission: 'authorAndAdmin',
    viewPermission: 'public',
    showComments: true,
    allowComments: true,
    showReactions: true,
    allowReactions: true,
    showShare: true,
    showReport: true,
    showInList: true,
    status: 'active',
  },
  {
    contentKey: 'deviceInfo',
    label: '디바이스정보',
    group: 'lounge',
    contentType: 'board',
    listPath: DEVICE_INFO_PATH,
    writePermission: 'verifiedUser',
    editPermission: 'authorAndAdmin',
    deletePermission: 'authorAndAdmin',
    viewPermission: 'public',
    showComments: false,
    allowComments: false,
    showReactions: false,
    allowReactions: false,
    showShare: true,
    showReport: true,
    showInList: true,
    status: 'active',
  },
  {
    contentKey: 'devLog',
    label: 'DevLog',
    group: 'lounge',
    contentType: 'board',
    listPath: DEV_LOG_PATH,
    writePermission: 'adminOnly',
    editPermission: 'adminOnly',
    deletePermission: 'adminOnly',
    viewPermission: 'public',
    showComments: false,
    allowComments: false,
    showReactions: false,
    allowReactions: false,
    showShare: true,
    showReport: true,
    showInList: true,
    status: 'active',
  },
  {
    contentKey: 'pics',
    label: 'Pics',
    group: 'snaps',
    contentType: 'gallery',
    listPath: PICS_PATH,
    writePermission: 'verifiedUser',
    editPermission: 'authorAndAdmin',
    deletePermission: 'authorAndAdmin',
    viewPermission: 'public',
    showComments: true,
    allowComments: true,
    showReactions: true,
    allowReactions: true,
    showShare: true,
    showReport: true,
    showInList: true,
    status: 'active',
  },
  {
    contentKey: 'picLog',
    label: 'picLog',
    group: 'snaps',
    contentType: 'gallery',
    listPath: PIC_LOG_PATH,
    writePermission: 'verifiedUser',
    editPermission: 'authorAndAdmin',
    deletePermission: 'authorAndAdmin',
    viewPermission: 'user',
    showComments: true,
    allowComments: true,
    showReactions: true,
    allowReactions: true,
    showShare: true,
    showReport: true,
    showInList: true,
    status: 'active',
  },
  {
    contentKey: 'clips',
    label: 'Clips',
    group: 'snaps',
    contentType: 'gallery',
    listPath: CLIPS_PATH,
    writePermission: 'verifiedUser',
    editPermission: 'authorAndAdmin',
    deletePermission: 'authorAndAdmin',
    viewPermission: 'public',
    showComments: true,
    allowComments: true,
    showReactions: true,
    allowReactions: true,
    showShare: true,
    showReport: true,
    showInList: true,
    status: 'active',
  },
];

export const writePermissionLabels: Record<ContentWritePermission, string> = {
  adminOnly: '관리자만',
  verifiedUser: '이메일 인증 회원',
  user: '로그인 회원',
  closed: '작성 불가',
};

export const editPermissionLabels: Record<ContentEditPermission, string> = {
  authorAndAdmin: '작성자와 관리자',
  adminOnly: '관리자만',
  closed: '수정 불가',
};

export const deletePermissionLabels: Record<ContentDeletePermission, string> = {
  authorAndAdmin: '작성자와 관리자',
  adminOnly: '관리자만',
};

export const viewPermissionLabels: Record<ContentViewPermission, string> = {
  public: '전체 공개',
  user: '로그인 회원',
  verifiedUser: '이메일 인증 회원',
  adminOnly: '관리자만',
};

export const contentStatusLabels: Record<ContentSettingStatus, string> = {
  active: '운영',
  readonly: '읽기 전용',
  hidden: '숨김',
};

export const reportStatusLabels: Record<ReportStatus, string> = {
  pending: '대기',
  reviewing: '검토 중',
  reviewed: '검토 완료',
  resolved: '처리 완료',
  rejected: '기각',
};

export const reportReasonLabels: Record<ReportReason, string> = {
  spam: '스팸',
  abuse: '욕설/괴롭힘',
  sexual: '성적 콘텐츠',
  violence: '폭력적 콘텐츠',
  illegal: '불법 행위',
  privacy: '개인정보 침해',
  copyright: '저작권 침해',
  other: '기타',
};
